### ISSUE TITLE
platformer needs a name

### ISSUE THREAD

**Issue by Torbin2** [Torbin2/platformer#10]
maybe: platform based, blue scaled, patfeorme, swap dié hap, flip to jump, flipaclip, amongus simulator, ytrewq, quertie, bpqd, chezz, cheesy adventures, need for speed, IShowCheese(Blocks), IFlipMe

**Comment by terukaaz** [comment]
We can basically make a poll or something, I think not changing the name is still ok, we will just call the "platformer" game "Torbin's platformer". Otherwise I suggest Cheezzflipper

![image](https://github.com/Torbin2/platformer/assets/88054829/9d2f12da-d8ba-49c5-9621-d50a0a6ab32c)

**Comment by terukaaz** [comment]
Platformer doesn't need really a name, because we're simply calling it "Torbin's platformer". I think everyone is ok with it, according to the amount of activities in the repo, closing the issue.
